# Generated by Django 3.1.1 on 2020-09-15 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloque',
            fields=[
                ('idbloque', models.AutoField(primary_key=True, serialize=False)),
                ('nombrebloque', models.CharField(max_length=100)),
                ('descbloque', models.CharField(max_length=1000, null=True)),
                ('iniciobloque', models.DateField(null=True)),
                ('finbloque', models.DateField(null=True)),
                ('fechacreacion', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Bloques',
                'db_table': 'bloques',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('idestado', models.AutoField(primary_key=True, serialize=False)),
                ('descestado', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Estados',
                'db_table': 'estados',
            },
        ),
        migrations.CreateModel(
            name='Prioridad',
            fields=[
                ('idprioridad', models.AutoField(primary_key=True, serialize=False)),
                ('descprioridad', models.CharField(max_length=50)),
                ('nivelprioridad', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Prioridades',
                'db_table': 'prioridades',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('idproyecto', models.AutoField(primary_key=True, serialize=False)),
                ('nombreproyecto', models.CharField(max_length=100)),
                ('descproyecto', models.CharField(max_length=500, null=True)),
                ('inicioproyecto', models.DateField(null=True)),
                ('finproyecto', models.DateField(null=True)),
                ('fechacreacion', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Proyectos',
                'db_table': 'proyectos',
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('idtarea', models.AutoField(primary_key=True, serialize=False)),
                ('nombretarea', models.CharField(max_length=100)),
                ('desctarea', models.CharField(max_length=5000, null=True)),
                ('fechacreacion', models.DateTimeField()),
                ('fechainicio', models.DateField(null=True)),
                ('fechafin', models.DateField(null=True)),
                ('fechaactualizacion', models.DateTimeField()),
                ('horasestimacion', models.IntegerField(null=True)),
                ('horasactuales', models.IntegerField(null=True)),
                ('horasrestantes', models.IntegerField(null=True)),
                ('bloques_idbloque', models.ForeignKey(db_column='bloques_idbloque', on_delete=django.db.models.deletion.CASCADE, related_name='bloque', to='Proyectos.bloque')),
                ('estados_idestado', models.ForeignKey(db_column='estados_idestado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estado', to='Proyectos.estado')),
                ('prioridades_idprioridad', models.ForeignKey(db_column='prioridades_idprioridad', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prioridad', to='Proyectos.prioridad')),
                ('proyectos_idproyecto', models.ForeignKey(db_column='proyectos_idproyecto', on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_tarea', to='Proyectos.proyecto')),
            ],
            options={
                'verbose_name_plural': 'Tareas',
                'db_table': 'tareas',
            },
        ),
        migrations.CreateModel(
            name='HistorialModificacionTarea',
            fields=[
                ('idhistorico', models.AutoField(primary_key=True, serialize=False)),
                ('fechahistorico', models.DateTimeField()),
                ('idusuario', models.IntegerField()),
                ('motivo', models.CharField(max_length=100)),
                ('deschistorico', models.TextField(max_length=1000, null=True)),
                ('tareas_idtarea', models.ForeignKey(db_column='tareas_idtarea', on_delete=django.db.models.deletion.CASCADE, to='Proyectos.tarea')),
            ],
            options={
                'verbose_name_plural': 'HistorialModificacionesTareas',
                'db_table': 'historialModificacionesTarea',
            },
        ),
        migrations.CreateModel(
            name='HistorialModificacionProyecto',
            fields=[
                ('idhistorico', models.AutoField(primary_key=True, serialize=False)),
                ('fechahistorico', models.DateTimeField()),
                ('idusuario', models.IntegerField()),
                ('motivo', models.CharField(max_length=100)),
                ('deschistorico', models.TextField(max_length=1000, null=True)),
                ('proyectos_idproyecto', models.ForeignKey(db_column='proyectos_idproyecto', on_delete=django.db.models.deletion.CASCADE, to='Proyectos.proyecto')),
            ],
            options={
                'verbose_name_plural': 'HistorialModificacionesProyectos',
                'db_table': 'historialModificacionesProyecto',
            },
        ),
        migrations.CreateModel(
            name='HistorialModificacionBloque',
            fields=[
                ('idhistorico', models.AutoField(primary_key=True, serialize=False)),
                ('fechahistorico', models.DateTimeField()),
                ('idusuario', models.IntegerField()),
                ('motivo', models.CharField(max_length=100)),
                ('deschistorico', models.TextField(max_length=1000, null=True)),
                ('bloques_idbloque', models.ForeignKey(db_column='tareas_idtarea', on_delete=django.db.models.deletion.CASCADE, to='Proyectos.bloque')),
            ],
            options={
                'verbose_name_plural': 'HistorialModificacionesBloques',
                'db_table': 'historialModificacionesBloque',
            },
        ),
        migrations.AddField(
            model_name='bloque',
            name='proyecto_idproyecto',
            field=models.ForeignKey(db_column='proyecto_idproyecto', on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_bloque', to='Proyectos.proyecto'),
        ),
        migrations.AddConstraint(
            model_name='tarea',
            constraint=models.UniqueConstraint(fields=('idtarea', 'bloques_idbloque'), name='constraint_tarea_bloque'),
        ),
        migrations.AddConstraint(
            model_name='tarea',
            constraint=models.UniqueConstraint(fields=('idtarea', 'estados_idestado'), name='constraint_tarea_estado'),
        ),
        migrations.AddConstraint(
            model_name='tarea',
            constraint=models.UniqueConstraint(fields=('idtarea', 'prioridades_idprioridad'), name='constraint_idtarea_prioridades'),
        ),
        migrations.AddConstraint(
            model_name='historialmodificaciontarea',
            constraint=models.UniqueConstraint(fields=('idhistorico', 'tareas_idtarea'), name='constraint_historico_tarea'),
        ),
        migrations.AddConstraint(
            model_name='historialmodificaciontarea',
            constraint=models.UniqueConstraint(fields=('idhistorico', 'idusuario'), name='constraint_historico_usuario_tarea'),
        ),
        migrations.AddConstraint(
            model_name='historialmodificacionproyecto',
            constraint=models.UniqueConstraint(fields=('idhistorico', 'proyectos_idproyecto'), name='constraint_historico_proyecto'),
        ),
        migrations.AddConstraint(
            model_name='historialmodificacionproyecto',
            constraint=models.UniqueConstraint(fields=('idhistorico', 'idusuario'), name='constraint_historico_usuario_proyecto'),
        ),
        migrations.AddConstraint(
            model_name='historialmodificacionbloque',
            constraint=models.UniqueConstraint(fields=('idhistorico', 'bloques_idbloque'), name='constraint_historico_bloque'),
        ),
        migrations.AddConstraint(
            model_name='historialmodificacionbloque',
            constraint=models.UniqueConstraint(fields=('idhistorico', 'idusuario'), name='constraint_historico_usuario_bloque'),
        ),
        migrations.AddConstraint(
            model_name='bloque',
            constraint=models.UniqueConstraint(fields=('idbloque', 'proyecto_idproyecto'), name='constraint_bloque_proyecto'),
        ),
    ]
