# Generated by Django 3.1.1 on 2020-09-09 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='fechaInicio',
            new_name='fechainicio',
        ),
    ]
