# Generated by Django 3.1.3 on 2020-11-16 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloque',
            fields=[
                ('idbloque', models.AutoField(primary_key=True, serialize=False)),
                ('nombrebloque', models.CharField(max_length=100)),
                ('descbloque', models.CharField(max_length=1000, null=True)),
                ('iniciobloque', models.DateField(null=True)),
                ('finbloque', models.DateField(null=True)),
                ('fechacreacion', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Bloques',
                'db_table': 'bloques',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('idestado', models.AutoField(primary_key=True, serialize=False)),
                ('descestado', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Estados',
                'db_table': 'estados',
            },
        ),
        migrations.CreateModel(
            name='HistorialModificacionBloque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'historial_modificacion_bloque',
            },
        ),
        migrations.CreateModel(
            name='HistorialModificaciones',
            fields=[
                ('idhistorico', models.AutoField(primary_key=True, serialize=False)),
                ('fechahistorico', models.DateTimeField()),
                ('motivo', models.CharField(max_length=100)),
                ('deschistorico', models.TextField(max_length=1000, null=True)),
                ('usuarios_idusuario', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'HistorialModificaciones',
                'db_table': 'historial_modificaciones',
            },
        ),
        migrations.CreateModel(
            name='HistorialModificacionProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historialModificaciones_idhistorial', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects.historialmodificaciones')),
            ],
            options={
                'db_table': 'historial_modificacion_proyecto',
            },
        ),
        migrations.CreateModel(
            name='HistorialModificacionTarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historialModificaciones_idhistorial', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects.historialmodificaciones')),
            ],
            options={
                'db_table': 'historial_modificacion_tarea',
            },
        ),
        migrations.CreateModel(
            name='Prioridad',
            fields=[
                ('idprioridad', models.AutoField(primary_key=True, serialize=False)),
                ('descprioridad', models.CharField(max_length=50)),
                ('nivelprioridad', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Prioridades',
                'db_table': 'prioridades',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('idproyecto', models.AutoField(primary_key=True, serialize=False)),
                ('nombreproyecto', models.CharField(max_length=100)),
                ('descproyecto', models.CharField(max_length=500, null=True)),
                ('inicioproyecto', models.DateField(null=True)),
                ('finproyecto', models.DateField(null=True)),
                ('fechacreacion', models.DateTimeField()),
                ('modificaciones', models.ManyToManyField(related_name='modificaciones_proyecto', through='projects.HistorialModificacionProyecto', to='projects.HistorialModificaciones')),
            ],
            options={
                'verbose_name_plural': 'Proyectos',
                'db_table': 'proyectos',
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('idtarea', models.AutoField(primary_key=True, serialize=False)),
                ('nombretarea', models.CharField(max_length=100)),
                ('desctarea', models.CharField(max_length=5000, null=True)),
                ('fechacreacion', models.DateTimeField()),
                ('fechainicio', models.DateField(null=True)),
                ('fechafin', models.DateField(null=True)),
                ('fechaactualizacion', models.DateTimeField()),
                ('horasestimacion', models.IntegerField(null=True)),
                ('horasactuales', models.IntegerField(null=True)),
                ('horasrestantes', models.IntegerField(null=True)),
                ('bloques_idbloque', models.ForeignKey(db_column='bloques_idbloque', on_delete=django.db.models.deletion.CASCADE, related_name='bloque', to='projects.bloque')),
                ('estados_idestado', models.ForeignKey(db_column='estados_idestado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estado', to='projects.estado')),
                ('modificaciones', models.ManyToManyField(related_name='modificaciones_tarea', through='projects.HistorialModificacionTarea', to='projects.HistorialModificaciones')),
                ('prioridades_idprioridad', models.ForeignKey(db_column='prioridades_idprioridad', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prioridad', to='projects.prioridad')),
                ('proyectos_idproyecto', models.ForeignKey(db_column='proyectos_idproyecto', on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_tarea', to='projects.proyecto')),
            ],
            options={
                'verbose_name_plural': 'Tareas',
                'db_table': 'tareas',
            },
        ),
        migrations.AddField(
            model_name='historialmodificaciontarea',
            name='tareas_idtarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects.tarea'),
        ),
        migrations.AddField(
            model_name='historialmodificacionproyecto',
            name='proyectos_idproyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects.proyecto'),
        ),
        migrations.AddConstraint(
            model_name='historialmodificaciones',
            constraint=models.UniqueConstraint(fields=('idhistorico', 'usuarios_idusuario'), name='constraint_historico_usuario_proyecto'),
        ),
        migrations.AddField(
            model_name='historialmodificacionbloque',
            name='bloques_idbloque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects.bloque'),
        ),
        migrations.AddField(
            model_name='historialmodificacionbloque',
            name='historialModificaciones_idhistorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects.historialmodificaciones'),
        ),
        migrations.AddField(
            model_name='bloque',
            name='modificaciones',
            field=models.ManyToManyField(related_name='modificaciones_bloque', through='projects.HistorialModificacionBloque', to='projects.HistorialModificaciones'),
        ),
        migrations.AddField(
            model_name='bloque',
            name='proyecto_idproyecto',
            field=models.ForeignKey(db_column='proyecto_idproyecto', on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_bloque', to='projects.proyecto'),
        ),
        migrations.AddConstraint(
            model_name='tarea',
            constraint=models.UniqueConstraint(fields=('idtarea', 'bloques_idbloque'), name='constraint_tarea_bloque'),
        ),
        migrations.AddConstraint(
            model_name='tarea',
            constraint=models.UniqueConstraint(fields=('idtarea', 'estados_idestado'), name='constraint_tarea_estado'),
        ),
        migrations.AddConstraint(
            model_name='tarea',
            constraint=models.UniqueConstraint(fields=('idtarea', 'prioridades_idprioridad'), name='constraint_idtarea_prioridades'),
        ),
        migrations.AlterUniqueTogether(
            name='historialmodificaciontarea',
            unique_together={('historialModificaciones_idhistorial', 'tareas_idtarea')},
        ),
        migrations.AlterUniqueTogether(
            name='historialmodificacionproyecto',
            unique_together={('historialModificaciones_idhistorial', 'proyectos_idproyecto')},
        ),
        migrations.AlterUniqueTogether(
            name='historialmodificacionbloque',
            unique_together={('historialModificaciones_idhistorial', 'bloques_idbloque')},
        ),
        migrations.AddConstraint(
            model_name='bloque',
            constraint=models.UniqueConstraint(fields=('idbloque', 'proyecto_idproyecto'), name='constraint_bloque_proyecto'),
        ),
    ]
