# Generated by Django 3.1.3 on 2021-04-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloque',
            name='descbloque',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='bloque',
            name='finbloque',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloque',
            name='iniciobloque',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='descproyecto',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='finproyecto',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='inicioproyecto',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='desctarea',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
