# Generated by Django 3.1.3 on 2021-04-19 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210406_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='bloques_idbloque',
            field=models.ForeignKey(db_column='bloques_idbloque', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bloque', to='projects.bloque'),
        ),
    ]
