# Generated by Django 3.0.8 on 2020-07-17 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloque',
            fields=[
                ('idbloque', models.AutoField(primary_key=True, serialize=False)),
                ('nombrebloque', models.CharField(max_length=100)),
                ('descbloque', models.CharField(max_length=1000)),
                ('fechacreacion', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Bloques',
                'db_table': 'bloques',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('idestado', models.AutoField(primary_key=True, serialize=False)),
                ('descestado', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Estados',
                'db_table': 'estados',
            },
        ),
        migrations.CreateModel(
            name='Prioridad',
            fields=[
                ('idprioridad', models.AutoField(primary_key=True, serialize=False)),
                ('descprioridad', models.CharField(max_length=50)),
                ('nivelprioridad', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Prioridades',
                'db_table': 'prioridades',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('idproyecto', models.AutoField(primary_key=True, serialize=False)),
                ('descproyecto', models.CharField(max_length=500)),
                ('inicioproyecto', models.DateField()),
                ('finproyecto', models.DateField()),
                ('fechacreacion', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Proyectos',
                'db_table': 'proyectos',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idrol', models.AutoField(primary_key=True, serialize=False)),
                ('descrol', models.CharField(max_length=45)),
                ('nivelrol', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('idtarea', models.AutoField(primary_key=True, serialize=False)),
                ('nombretarea', models.CharField(max_length=100)),
                ('desctarea', models.CharField(max_length=5000)),
                ('fechacreacion', models.DateTimeField()),
                ('fechaInicio', models.DateField()),
                ('fechafin', models.DateField()),
                ('fechaactualizacion', models.DateTimeField()),
                ('bloques_idbloque', models.ForeignKey(db_column='bloques_idbloque', on_delete=django.db.models.deletion.CASCADE, to='Login.Bloque')),
                ('estados_idestado', models.ForeignKey(db_column='estados_idestado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Login.Estado')),
                ('prioridades_idprioridad', models.ForeignKey(db_column='prioridades_idprioridad', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Login.Prioridad')),
            ],
            options={
                'verbose_name_plural': 'Tareas',
                'db_table': 'tareas',
            },
        ),
        migrations.CreateModel(
            name='Tareasusuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tareas_idtarea', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Login.Tarea')),
            ],
            options={
                'db_table': 'tareasusuario',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('primerapellido', models.CharField(max_length=45)),
                ('segundoapellido', models.CharField(blank=True, max_length=45, null=True)),
                ('telefono', models.CharField(blank=True, max_length=12, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=200)),
                ('fecharegistro', models.DateTimeField()),
                ('estado', models.IntegerField(choices=[(0, 'Inhabilitado'), (1, 'Habilitado')], default=0)),
                ('roles_idrol', models.ForeignKey(blank=True, db_column='roles_idrol', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Login.Rol')),
                ('tareas', models.ManyToManyField(through='Login.Tareasusuario', to='Login.Tarea')),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
            },
        ),
        migrations.AddField(
            model_name='tareasusuario',
            name='usuarios_idusuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Login.Usuario'),
        ),
        migrations.CreateModel(
            name='RegistroEntradaUsuario',
            fields=[
                ('idregistroacceso', models.AutoField(primary_key=True, serialize=False)),
                ('fechaacceso', models.DateField()),
                ('horaacceso', models.TimeField()),
                ('ipacceso', models.CharField(max_length=45)),
                ('usuario_idusuario', models.ForeignKey(db_column='usuario_idusuario', on_delete=django.db.models.deletion.DO_NOTHING, to='Login.Usuario')),
            ],
            options={
                'verbose_name_plural': 'Registroentradausuarios',
                'db_table': 'registroEntradaUsuarios',
            },
        ),
        migrations.CreateModel(
            name='HistorialModificacionTarea',
            fields=[
                ('idhistorico', models.AutoField(primary_key=True, serialize=False)),
                ('fechahistorico', models.DateField()),
                ('horahistorico', models.TimeField()),
                ('idusuario', models.IntegerField()),
                ('tareas_idtarea', models.ForeignKey(db_column='tareas_idtarea', on_delete=django.db.models.deletion.CASCADE, to='Login.Tarea')),
            ],
            options={
                'verbose_name_plural': 'HistorialModificacionesTareas',
                'db_table': 'historialModificacionesTareas',
            },
        ),
        migrations.AddField(
            model_name='bloque',
            name='proyecto_idproyecto',
            field=models.ForeignKey(db_column='proyecto_idproyecto', on_delete=django.db.models.deletion.CASCADE, to='Login.Proyecto'),
        ),
        migrations.AddConstraint(
            model_name='tareasusuario',
            constraint=models.UniqueConstraint(fields=('tareas_idtarea', 'usuarios_idusuario'), name='constraint_tareas_usuario'),
        ),
        migrations.AddConstraint(
            model_name='tarea',
            constraint=models.UniqueConstraint(fields=('idtarea', 'bloques_idbloque'), name='constraint_tarea_bloque'),
        ),
        migrations.AddConstraint(
            model_name='tarea',
            constraint=models.UniqueConstraint(fields=('idtarea', 'estados_idestado'), name='constraint_tarea_estado'),
        ),
        migrations.AddConstraint(
            model_name='tarea',
            constraint=models.UniqueConstraint(fields=('idtarea', 'prioridades_idprioridad'), name='constraint_idtarea_prioridades'),
        ),
        migrations.AddConstraint(
            model_name='historialmodificaciontarea',
            constraint=models.UniqueConstraint(fields=('idhistorico', 'tareas_idtarea'), name='constraint_historico_tarea'),
        ),
        migrations.AddConstraint(
            model_name='historialmodificaciontarea',
            constraint=models.UniqueConstraint(fields=('idhistorico', 'idusuario'), name='constraint_historico_usuario'),
        ),
        migrations.AddConstraint(
            model_name='bloque',
            constraint=models.UniqueConstraint(fields=('idbloque', 'proyecto_idproyecto'), name='constraint_bloque_proyecto'),
        ),
    ]
