# Generated by Django 3.0.8 on 2020-07-30 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idrol', models.AutoField(primary_key=True, serialize=False)),
                ('descrol', models.CharField(max_length=45)),
                ('nivelrol', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Tareasusuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tareas_idtarea', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Proyectos.Tarea')),
            ],
            options={
                'db_table': 'tareasusuario',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('primerapellido', models.CharField(max_length=45)),
                ('segundoapellido', models.CharField(blank=True, max_length=45, null=True)),
                ('telefono', models.CharField(blank=True, max_length=12, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=200)),
                ('fecharegistro', models.DateTimeField()),
                ('estado', models.IntegerField(choices=[(0, 'Inhabilitado'), (1, 'Habilitado')], default=0)),
                ('roles_idrol', models.ForeignKey(blank=True, db_column='roles_idrol', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Login.Rol')),
                ('tareas', models.ManyToManyField(through='Login.Tareasusuario', to='Proyectos.Tarea')),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
            },
        ),
        migrations.AddField(
            model_name='tareasusuario',
            name='usuarios_idusuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Login.Usuario'),
        ),
        migrations.CreateModel(
            name='RegistroEntradaUsuario',
            fields=[
                ('idregistroacceso', models.AutoField(primary_key=True, serialize=False)),
                ('fechaacceso', models.DateField()),
                ('horaacceso', models.TimeField()),
                ('ipacceso', models.CharField(max_length=45)),
                ('usuario_idusuario', models.ForeignKey(db_column='usuario_idusuario', on_delete=django.db.models.deletion.DO_NOTHING, to='Login.Usuario')),
            ],
            options={
                'verbose_name_plural': 'Registroentradausuarios',
                'db_table': 'registroEntradaUsuarios',
            },
        ),
        migrations.AddConstraint(
            model_name='tareasusuario',
            constraint=models.UniqueConstraint(fields=('tareas_idtarea', 'usuarios_idusuario'), name='constraint_tareas_usuario'),
        ),
    ]
