# Generated by Django 3.0.8 on 2020-07-20 16:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='nombreproyecto',
            field=models.CharField(default=datetime.datetime(2020, 7, 20, 16, 54, 47, 704752, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
