# Generated by Django 3.1.1 on 2020-09-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tareasusuarios',
            name='constraint_tareas_usuario',
        ),
        migrations.AlterUniqueTogether(
            name='tareasusuarios',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='tareasusuarios',
            constraint=models.UniqueConstraint(fields=('tareas_idtarea', 'usuarios_idusuario'), name='constraint_tareas_usuario'),
        ),
        migrations.RemoveField(
            model_name='tareasusuarios',
            name='bloques_idbloque',
        ),
        migrations.RemoveField(
            model_name='tareasusuarios',
            name='proyectos_idproyecto',
        ),
    ]
