# Generated by Django 3.0.8 on 2020-08-06 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='permisos',
            field=models.ManyToManyField(through='Login.PermisosRoles', to='Login.Permisos'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='roles',
            field=models.ManyToManyField(through='Login.RolesUsuarios', to='Login.Rol'),
        ),
        migrations.AlterField(
            model_name='permisosroles',
            name='permisos_idpermiso',
            field=models.ForeignKey(db_column='permisos_idpermiso', on_delete=django.db.models.deletion.DO_NOTHING, related_name='permisos', to='Login.Permisos'),
        ),
        migrations.AlterField(
            model_name='permisosroles',
            name='roles_idrol',
            field=models.ForeignKey(db_column='roles_idrol', on_delete=django.db.models.deletion.DO_NOTHING, related_name='roles', to='Login.Rol'),
        ),
    ]
