# Generated by Django 3.1.3 on 2021-04-06 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210406_1856'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectosUsuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyectos_idproyecto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects.proyecto')),
                ('usuarios_idusuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.usuario')),
            ],
            options={
                'db_table': 'proyectos_usuario',
            },
        ),
        migrations.CreateModel(
            name='BloquesUsuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloques_idbloque', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects.bloque')),
                ('usuarios_idusuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.usuario')),
            ],
            options={
                'db_table': 'bloques_usuario',
            },
        ),
        migrations.AddConstraint(
            model_name='proyectosusuarios',
            constraint=models.UniqueConstraint(fields=('proyectos_idproyecto', 'usuarios_idusuario'), name='constraint_proyectos_usuario'),
        ),
        migrations.AddConstraint(
            model_name='bloquesusuarios',
            constraint=models.UniqueConstraint(fields=('bloques_idbloque', 'usuarios_idusuario'), name='constraint_bloques_usuario'),
        ),
    ]
