# Generated by Django 3.1.3 on 2021-04-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210406_1856'),
        ('users', '0002_auto_20210406_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='bloques',
            field=models.ManyToManyField(related_name='bloques', through='users.BloquesUsuarios', to='projects.Bloque'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='proyectos',
            field=models.ManyToManyField(related_name='proyectos', through='users.ProyectosUsuarios', to='projects.Proyecto'),
        ),
    ]
