# Generated by Django 3.1.3 on 2021-04-07 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210406_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareasusuarios',
            name='usuarios_idusuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.usuario'),
        ),
    ]
