# Generated by Django 3.1.3 on 2021-04-09 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210407_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectosusuarios',
            name='usuarios_idusuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
