# Generated by Django 3.1.3 on 2021-04-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210409_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecharegistro',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
