# Generated by Django 3.1.3 on 2021-04-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210409_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='permisos',
            name='idcodigo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
